# Permalinks
permalink:           pretty

# Setup
title:               Valenceo
tagline:             welcome!
url:                 http://blog.valenceo.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Matt Hayden
  url:               https://github.com/Valenceo
  email:             webmaster+blog@valenceo.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/Valenceo/blog-valenceo
google_analytics:
  id:                UA-102590217-1

# Gems
gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
